FROM grafana/grafana
COPY ./automatic.yml /etc/grafana/provisioning/datasources/
COPY ./dashboards.yml /etc/grafana/provisioning/dashboards/
COPY ./Dashboard-1652786911207.json /etc/grafana/provisioning/dashboards/
COPY ./grafana.db /var/lib/grafana/
